POST http://localhost:8080/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDM4ODY2OTEsInVzZXJuYW1lIjoiam9obl9kb2UxIn0.NzrLxIyujq-wLwcuUOLlKfOCISXe6XdpuYWysiXAgks

{
  "name": "Personal2",
  "color" : "red"
}
